# Generated by Django 3.2.3 on 2021-05-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('admin', '관리자'), ('user', '사용자')], default='user', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
